import type { Metadata } from "next";
import "./globals.css";
import { Inter, IBM_Plex_Mono } from "next/font/google";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	display: "swap",
});

const ibm_plex_mono = IBM_Plex_Mono({
	weight: ["300", "400", "500", "600", "700"],
	style: ["normal", "italic"],
	variable: "--font-ibm-plex-mono",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${ibm_plex_mono.variable}`}>
				{children}
			</body>
		</html>
	);
}
