"use client";
import React from "react";
import { QUERIES } from "../constants";
// import type { Metadata } from "next";
import Head from "next/head";
import { ibmPlexMono } from "../fonts";
import NavBar from "@/components/NavBar";
import styled from "styled-components";
import GlobalStyles from "@/lib/GlobalStyles";
import StyledComponentsRegistry from "@/lib/StyledComponentsRegistry";

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<Head>
				<title>Emily Dev Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<html lang="en" className={ibmPlexMono.className}>
				<body>
					<GlobalStyles />
					<PageWrapper>
						<Nav>
							<NavBar />
						</Nav>
						<Main>
							<StyledComponentsRegistry>{children}</StyledComponentsRegistry>
						</Main>
						<Footer>
							<FooterContent>Emily Berryman © </FooterContent>
						</Footer>
					</PageWrapper>
				</body>
			</html>
		</>
	);
}

const PageWrapper = styled.div`
	display: grid;
	grid-template-rows: 2.5rem 1fr 2rem;
	grid-template-columns: 1fr 1fr 1fr;
	grid-template-areas:
		"header header header"
		"main main main"
		"footer footer footer";
`;

const Nav = styled.div`
	grid-area: header;
	border-bottom: 1px solid grey;
	display: flex;
	justify-content: flex-end;
	align-items: center;
	padding: 0 24px;
	position: sticky;
	top: 0;
	z-index: 2;
	background: var(--white);

	@media ${QUERIES.mobileAndDown} {
		justify-content: center;
	}
`;

const Main = styled.main`
	grid-area: main;
	overflow: hidden;
`;

const Footer = styled.footer`
	grid-area: footer;
	display: grid;
	place-content: center;
	border-top: 2px dotted black;
`;

const FooterContent = styled.span`
	font-family: "IBM Plex Mono", "serif";
	font-size: 0.8125rem;
	font-weight: 300;
	letter-spacing: 0.3rem;
	text-transform: uppercase;
`;
